# Generated by Django 3.1.4 on 2021-02-13 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20210214_0148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='sno',
            new_name='Sno',
        ),
    ]
