# Generated by Django 3.1.4 on 2021-02-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20210214_0149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Sno',
        ),
        migrations.AddField(
            model_name='contact',
            name='id',
            field=models.AutoField(auto_created=True, default='', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
